services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/backend-service:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-network
    restart: always

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/frontend-service:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network: