apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Adjust based on your needs

    scrape_configs:
      # Scrape metrics from the Node.js app
      - job_name: "nodejs-app"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["express-service.default.svc.cluster.local:80"]

      # # Scrape container metrics from the kubelet
      # - job_name: "kubelet-cadvisor"
      #   metrics_path: "/metrics/cadvisor"
      #   scheme: http
      #   static_configs:
      #     - targets: ["192.168.49.2:10250"]
      #   tls_config:
      #     insecure_skip_verify: true
